### ISSUE TITLE
halite state.highstate Error retcode = 2

### ISSUE THREAD

**Issue by aboe76** [saltstack/halite#32]
After starting halite, and logging in with my user,
I saw that halite also tracks and shows commands run from command line
in the event bus.

So I opened another terminal and did 
salt -a pam * state.highstate as my user to see if it works.

and got this error in the debug log 

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 33704)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

But the state execution is succesfull

In halite it shows retcode 2 as a red job, but if I run the same command on cli the return code is 0.

```
salt/job/20130914213750579421/ret/salt.example.com/2013-09-14_21:37:58.484030 
_stamp: 2013-09-14_21:37:58.484030
cmd: _return
fun: state.highstate
id: salt.example.com
jid: 20130914213750579421
out: highstate
retcode: 2
return: 
success: true
salt/job/20130914213750579421/new/2013-09-14_21:37:50.580023 
_stamp: 2013-09-14_21:37:50.580023
arg: [ ]
fun: state.highstate
jid: 20130914213750579421
minions: [ salt.example.com ]
tgt: *
tgt_type: glob
user: example
```

Moments later a green job appears in the event bus, telling me what I already knew:
Job executed success: true.

```
salt/job/20130914213756505397/ret/salt.example.com/2013-09-14_21:37:56.577241 
_stamp: 2013-09-14_21:37:56.577241
cmd: _return
fun: saltutil.find_job
id: salt.example.com
jid: 20130914213756505397
retcode: 0
return: 
success: true
salt/job/20130914213756505397/new/2013-09-14_21:37:56.513037 
_stamp: 2013-09-14_21:37:56.513037
arg: [ 20130914213750579421 ]
fun: saltutil.find_job
jid: 20130914213756505397
minions: [ salt.example.com ]
tgt: *
tgt_type: glob
user: example
```

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
